name: Deploy Cloud Funcstions

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        project_id: taiki-gcp
        service_account_email: taiki-gcp@appspot.gserviceaccount.com
        service_account_key: ${{ secrets.GCP_SECRET }}
        export_default_credentials: true

    - name: Deploy Functions
      run: sh app/deploy/deploy.sh
